Use list instead of array
Epistimio/orion pull request #1050
Opened 2022-12-20 13:43 UTC by bouthilx

Numpy does not seam to support anymore non homogeneous arrays (for shapes at least). We don't need an array, so we should rather use lists.

2022-12-20 15:22 UTC, Delaunay approved these changes

2022-12-21 21:44 UTC, lebrice requested changes

2022-12-21 21:44 UTC, lebrice commented on tests/unittests/algo/test_tpe.py
>  def _trial_to_array(trial: Trial, space: Space) -> np.ndarray:
The typing would be wrong.
```suggestion
def _trial_to_array(trial: Trial, space: Space) -> list[tuple]:
```

2022-12-21 21:45 UTC, lebrice approved these changes

2023-01-05 17:19 UTC, Delaunay commented
The issue here is dependencies using the deprecated np.object.
orion phased it out recently but dependencies are still using it and the object was removed in the latest numpy release
we will have to downgrade numpy on our side to keep the compatibility

2023-01-11 14:12 UTC, merged